    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install requests
        run: pip install requests

      - name: Run AI Shorts Machine
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python main.py
      - name: Save generated script
        uses: actions/upload-artifact@v4
        with:
          name: generated-script
          path: script.txt
